export const BASKET_CREATE_REQUEST = "BASKET_CREATE_REQUEST";
export const BASKET_CREATE_SUCCESS = "BASKET_CREATE_SUCCESS";
export const BASKET_CREATE_FAIL = "BASKET_CREATE_FAIL";

export const BASKET_DELETE_REQUEST = "BASKET_DELETE_REQUEST";
export const BASKET_DELETE_SUCCESS = "BASKET_DELETE_SUCCESS";
export const BASKET_DELETE_FAIL = "BASKET_DELETE_FAIL";

export const CLEAR_BASKET_SUCCESS = "CLEAR_BASKET_SUCCESS";
export const CLEAR_BASKET_FAIL = "CLEAR_BASKET_FAIL";

export const BASKET_DETAILS_REQUEST = "BASKET_DETAILS_REQUEST";
export const BASKET_DETAILS_SUCCESS = "BASKET_DETAILS_SUCCESS";
export const BASKET_DETAILS_FAIL = "BASKET_DETAILS_FAIL";

export const BASKET_PAY_REQUEST = "BASKET_PAY_REQUEST";
export const BASKET_PAY_SUCCESS = "BASKET_PAY_SUCCESS";
export const BASKET_PAY_FAIL = "BASKET_PAY_FAIL";
export const BASKET_PAY_RESET = "BASKET_PAY_RESET";

export const BASKET_LIST_MY_REQUEST = "BASKET_LIST_MY_REQUEST";
export const BASKET_LIST_MY_SUCCESS = "BASKET_LIST_MY_SUCCESS";
export const BASKET_LIST_MY_FAIL = "BASKET_LIST_MY_FAIL";
export const BASKET_LIST_MY_RESET = "BASKET_LIST_MY_RESET";

export const BASKET_LIST_ALL_REQUEST = "BASKET_LIST_ALL_REQUEST";
export const BASKET_LIST_ALL_SUCCESS = "BASKET_LIST_ALL_SUCCESS";
export const BASKET_LIST_ALL_FAIL = "BASKET_LIST_ALL_FAIL";

export const BASKET_DELIVER_REQUEST = "BASKET_DELIVER_REQUEST";
export const BASKET_DELIVER_SUCCESS = "BASKET_DELIVER_SUCCESS";
export const BASKET_DELIVER_FAIL = "BASKET_DELIVER_FAIL";
export const BASKET_DELIVER_RESET = "BASKET_DELIVER_RESET";
