export const NAV_LIST_REQUEST = "NAV_LIST_REQUEST";
export const NAV_LIST_SUCCESS = "NAV_LIST_SUCCESS";
export const NAV_LIST_FAIL = "NAV_LIST_FAIL";

export const NAV_CATEGORY_REQUEST = "NAV_CATEGORY_REQUEST";
export const NAV_CATEGORY_SUCCESS = "NAV_CATEGORY_SUCCESS";
export const NAV_CATEGORY_FAIL = "NAV_CATEGORY_FAIL";
